### ISSUE TITLE
Drawing with grain - is it possible?

### ISSUE THREAD

**Issue by palikacska** [CWBudde/AggPasMod#11]
I know this question will be a little bit absurd.

I would like to use AggPasMod for non-anti-aliased drawing just for performance reasons.

Would you recommend it? Is it even possible? To draw without anti-aliasing?

It would be necessary for programming a really fast RDP client with all its drawing primitives. It must run on really slow computers as well.

**Comment by CWBudde** [comment]
Yes, it can be used to draw non-anti-aliased, but I guess it won't be much fast as it uses more or less the same algorithms. So in the end there won't be a benefit of using non-anti-aliased drawing.

In your case I would probably use Graphics32 instead. It is very fast at drawing non-anti-aliased, but also offers fast anti-aliased drawing. It even contains a port of a AggPasMod renderer (which itself is a port of the FreeType renderer).
