### ISSUE TITLE
TAgg2DControl.AssignTo doesn't work in Free Pascal 

### ISSUE THREAD

**Issue by Akira13641** [CWBudde/AggPasMod#3]
Using either Free Pascal 3.0 or Free Pascal 3.1.1 trunk, with either Lazarus 1.4.4, Lazarus 1.6RC2, or Lazarus Trunk, attempting to use this method always gives the error "Cannot assign a TAgg2DControl to a TAgg2DControl." I'm on Windows 10 64-Bit. The only way I've found around this so far is to add a new public property to TAggCustomAgg2DContol that gives direct access to the pixel map, i.e:

property PixelMap: TPixelMap read FPixelMap write FPixelMap;

I'm then able to use the the "PixelMap.Assign" function without any problems.

**Comment by CWBudde** [comment]
I added a simple read access to the pixel map. This should be sufficient to call PixelMap.Assign.
