### ISSUE TITLE
Bug alpha calculation in AggPixelFormatBgra32Pre.inc BlendPixBgraPre asm

### ISSUE THREAD

**Issue by BVerhue** [CWBudde/AggPasMod#6]
Hi, there is a small bug in the asm:

```
//MOVZX   EDX, [EDI] should be:
MOVZX   EDX, [EDI +$3]
SUB     EAX, EDX
IMUL    EAX, EBX
SHR     EAX, $08
MOV     EDX, CAggBaseMask
SUB     EDX, EAX
MOV     [EDI + $3], DL
```

and
    //MOVZX   EDX, [RCX]
    MOVZX   EDX, [RCX +$3]
    SUB     EAX, EDX
    IMUL    EAX, R10
    SHR     EAX, $08
    MOV     EDX, CAggBaseMask
    SUB     EDX, EAX
    MOV     [RCX + $3], DL

By the way, since I want to use the library in some of my projects, I would like to contribute. I found some issues with the freetype implementation also and some other things.

Regards
Bruno

**Comment by CWBudde** [comment]
The issue has been fixed. Regarding a contribution: Feel free to either fork the repository or send patches / annotations or post everything you find as an issue here. It's not top priority, but I'll surely take care that contributions make their way into the code.

**Comment by BVerhue** [comment]
Ok, thanks.

I forked the repository

Bruno

2016-11-01 13:27 GMT+01:00 Christian Budde notifications@github.com:
